packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  '@oxlint/plugins': 1.82.0
  '@types/node': ^26.6.1
  genbumppush: ^0.0.6
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@0.3.2
  vite-plus: 0.3.2

overrides:
  vite@*: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
