import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vite-plus';

export default defineConfig({
  resolve: {
    alias: {
      '~': fileURLToPath(new URL('./apps/api', import.meta.url)),
    },
  },
  staged: {
    '*': 'pnpm exec varlock scan --staged',
    '*.{ts,vue,css,json,md,yaml}': 'vp fmt',
    '*.{ts,vue}': 'vp lint',
  },
  fmt: {
    sortImports: {
      groups: [
        'type-import',
        'type-internal',
        ['type-parent', 'type-sibling', 'type-index'],
        ['value-builtin', 'value-external'],
        'value-internal',
        ['value-parent', 'value-sibling', 'value-index'],
        'unknown',
      ],
      newlinesBetween: false,
    },
    sortTailwindcss: {
      stylesheet: 'apps/web/app/assets/css/main.css',
      attributes: ['class'],
      functions: ['clsx', 'cn'],
      preserveWhitespace: true,
    },
    singleAttributePerLine: true,
    vueIndentScriptAndStyle: true,
    sortPackageJson: false,
    singleQuote: true,
    ignorePatterns: ['CHANGELOG.md', '.agents/**', 'tools/oxlint/anti-slop/**'],
  },
  lint: {
    plugins: ['typescript', 'unicorn', 'import', 'vue', 'oxc'],
    jsPlugins: [
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin',
      },
      {
        name: 'anti-slop',
        specifier: './tools/oxlint/anti-slop/index.ts',
      },
    ],
    categories: {
      correctness: 'error',
      suspicious: 'warn',
      perf: 'warn',
    },
    rules: {
      'vite-plus/prefer-vite-plus-imports': 'error',

      'no-console': [
        'warn',
        {
          allow: ['warn', 'error', 'info'],
        },
      ],
      'no-debugger': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      'eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],

      'typescript/no-floating-promises': 'error',
      'typescript/no-misused-promises': 'error',
      'typescript/await-thenable': 'error',
      'typescript/no-unsafe-assignment': 'warn',
      'typescript/no-unsafe-argument': 'error',
      'typescript/no-unsafe-call': 'error',
      'typescript/no-unsafe-member-access': 'error',
      'typescript/no-unsafe-return': 'error',
      'typescript/no-implied-eval': 'error',
      'typescript/only-throw-error': 'error',
      'typescript/require-array-sort-compare': 'error',
      'typescript/no-deprecated': 'warn',
      'typescript/require-await': 'warn',
      'typescript/restrict-template-expressions': 'warn',
      'typescript/unbound-method': 'error',
      'typescript/switch-exhaustiveness-check': 'warn',
      'typescript/prefer-nullish-coalescing': 'warn',
      'typescript/prefer-optional-chain': 'warn',
      'typescript/no-explicit-any': 'warn',
      'typescript/no-non-null-assertion': 'warn',
      'typescript/consistent-type-imports': 'warn',
      'typescript/consistent-type-exports': 'warn',
      'typescript/no-import-type-side-effects': 'error',
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-duplicate-type-constituents': 'error',
      'typescript/no-redundant-type-constituents': 'error',
      'typescript/no-misused-spread': 'error',
      'typescript/no-base-to-string': 'error',
      'typescript/no-array-delete': 'error',
      'typescript/no-for-in-array': 'error',
      'typescript/no-meaningless-void-operator': 'error',
      'typescript/no-confusing-non-null-assertion': 'warn',
      'typescript/no-confusing-void-expression': 'warn',
      'typescript/ban-ts-comment': 'warn',
      'typescript/consistent-generic-constructors': 'warn',
      'typescript/consistent-indexed-object-style': 'warn',
      'typescript/array-type': 'warn',
      'typescript/no-inferrable-types': 'warn',
      'typescript/no-empty-object-type': 'warn',
      'typescript/no-invalid-void-type': 'warn',
      'typescript/no-dynamic-delete': 'warn',
      'typescript/no-namespace': 'warn',
      'typescript/no-require-imports': 'warn',
      'typescript/adjacent-overload-signatures': 'warn',

      'vue/no-dupe-keys': 'error',
      'vue/no-deprecated-data-object-declaration': 'error',
      'vue/no-deprecated-delete-set': 'error',
      'vue/no-deprecated-destroyed-lifecycle': 'error',
      'vue/no-deprecated-events-api': 'error',
      'vue/no-deprecated-model-definition': 'error',
      'vue/no-deprecated-props-default-this': 'error',
      'vue/no-deprecated-vue-config-keycodes': 'error',
      'vue/no-async-in-computed-properties': 'error',
      'vue/no-side-effects-in-computed-properties': 'error',
      'vue/no-computed-properties-in-data': 'error',
      'vue/no-lifecycle-after-await': 'error',
      'vue/no-expose-after-await': 'error',
      'vue/no-arrow-functions-in-watch': 'error',
      'vue/no-export-in-script-setup': 'error',
      'vue/no-reserved-component-names': 'error',
      'vue/no-reserved-keys': 'error',
      'vue/no-reserved-props': 'error',
      'vue/no-required-prop-with-default': 'warn',
      'vue/no-shared-component-data': 'error',
      'vue/no-multiple-slot-args': 'error',
      'vue/no-import-compiler-macros': 'warn',
      'vue/define-props-declaration': 'warn',
      'vue/define-emits-declaration': 'warn',
      'vue/next-tick-style': 'warn',
      'vue/component-definition-name-casing': 'warn',
      'vue/valid-define-props': 'error',
      'vue/valid-define-emits': 'error',
      'vue/valid-define-options': 'error',
      'vue/valid-next-tick': 'error',
      'vue/no-watch-after-await': 'error',
      'vue/return-in-computed-property': 'error',
      'vue/return-in-emits-validator': 'error',
      'vue/prefer-import-from-vue': 'error',

      'unicorn/no-instanceof-array': 'warn',
      'unicorn/no-invalid-fetch-options': 'error',
      'unicorn/no-invalid-remove-event-listener': 'error',
      'unicorn/no-thenable': 'error',
      'unicorn/no-await-in-promise-methods': 'error',
      'unicorn/catch-error-name': 'warn',
      'unicorn/error-message': 'warn',
      'unicorn/no-new-array': 'warn',
      'unicorn/no-null': 'off',

      'import/no-duplicates': 'error',
      'import/no-cycle': 'warn',
      'import/no-self-import': 'error',
      'import/no-mutable-exports': 'warn',
      'import/newline-after-import': 'warn',

      'oxc/no-accumulating-spread': 'error',

      'anti-slop/no-array-filter-map': 'error',
      'anti-slop/no-reduce-accumulator-copy': 'error',
      'anti-slop/no-chained-type-assertions': 'error',
      'anti-slop/no-conditional-empty-object-spread': 'error',
      'anti-slop/no-known-value-widening': 'error',
      'anti-slop/no-module-mocking': 'error',
      'anti-slop/no-object-parameters': 'error',
      'anti-slop/no-reflect-apply': 'error',
      'anti-slop/no-reflect-get': 'error',
      'anti-slop/no-runtime-typeof': 'error',
      'anti-slop/no-shape-in-symbol-names': 'error',
      'anti-slop/no-unknown-parameters': 'error',
      'anti-slop/no-unknown-returns': 'error',
      'anti-slop/no-unknown-type-aliases': 'error',
      'anti-slop/no-unsafe-dictionary-type': 'error',
      'anti-slop/no-widen-then-assert': 'error',
      'anti-slop/require-safety-comment-for-type-assertion': 'error',
    },
    options: {
      typeAware: true,
      typeCheck: true,
    },
    ignorePatterns: ['**/*.d.ts', '.agents/**', 'tools/oxlint/anti-slop/**'],
  },
  test: {
    passWithNoTests: true,
  },
  run: {
    cache: {
      tasks: true,
      scripts: false,
    },
  },
});
